baseURL = 'https://www.theterminal.cafe/'
languageCode = 'en-us'
title = "The Terminal Cafe || Your single destination for everything tech and opensource"
summaryLength = '10'

[menu]
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news"
    weight = 20

  [[menu.main]]
    identifier = "tutorial"
    name = "Tutorials"
    url = "/tutorials"
    weight = 30

  [[menu.main]]
    identifier = "hub"
    name = "Hub"
    url = "/hub"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/admin/team"
    weight = 50


[taxonomies]
    tag = "tags"
    category = "categories"



[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = 'categories'
    weight = 100
    
  [[related.indices]]
    name = 'tags'
    weight = 10
